### ISSUE TITLE
大数据（5.4G）出现编码问题了

### ISSUE THREAD

**Issue by mjj1094** [dreamszl/dtopwords#4]
之前运行的小数据500M以内没有问题，但是换成大数据了，总是报错。只把报错的句子部分运行又不报错了。
Traceback (most recent call last):
  File "pipeline.py", line 103, in <module>
    generate_domain_words(src_path, dtop_res_path)
  File "/home/mjj/project/H/dtopwords.py", line 336, in generate_domain_words
    initialize_static_files(trg_files)
  File "/home/mjj/project/H/dtopwords.py", line 99, in initialize_static_files
    init_dict(tfp, cnp, inp)
  File "/home/mjj/project/H/dtopwords.py", line 106, in init_dict
    generate_all_ngram(src_path, cn_path, len_threshold, fre_threshold, splitor=splitor)
  File "/home/mjj/project/H/ngram.py", line 486, in generate_all_ngram
    generate_large_ngram_by_filtering(input_file_path, input_file_path + '_tmp%d' % i, gram_num=i, filter_num=filter_num, sort=True, filter_function=punctuation_filter, merge=False, splitor
=splitor)  File "/home/mjj/project/H/ngram.py", line 265, in generate_large_ngram_by_filtering
    get_ngram(gram_num, piece_file_path, piece_ngram_path, filter_num=filter_num, preprocessor=preprocessor, splitor=splitor)
  File "/home/mjj/project/H/ngram.py", line 135, in get_ngram
    segs = [a.encode('utf-8') for a in list(line.decode('utf-8'))]
  File "/home/mjj/virtualenv/py2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe6 in position 79: unexpected end of data

**Comment by mjj1094** [comment]
好的，谢谢！

在 2019-01-25 20:29:09，"Ao Chen" <notifications@github.com> 写道：


最新版本已解决该问题。
另外目前的算法实现最初只是作为论文的 demo 并没有针对大语料进行效率优化，在 5.4g 大小的数据上跑可能需要较长的时间。另外可能需要修改 dtopwords.py 245 行的 4000 为更大的数值，避免进程过多。
